### ISSUE TITLE
Install USWDS theme

### ISSUE THREAD

**Issue by kevwalsh** [CivicActions/fema-grants#4]
Install https://www.drupal.org/project/uswds

or  https://github.com/CivicActions/d8-uswds-theme

**Comment by bobschmitt-civicactions** [comment]
Pull request: https://github.com/CivicActions/fema-grants/pull/23

Assigning to Gerardo for merging...

**Comment by kevwalsh** [comment]
So no child theme?

**Comment by kevwalsh** [comment]
Also i see package-lock.json but no package.json. Which means that 

```
npm install
cp -r node_modules/uswds/dist assets
npm run build
``` 

fails.

**Comment by kevwalsh** [comment]
PR: #29
