### ISSUE TITLE
Bug when assigning a report to a specialist

### ISSUE THREAD

**Issue by bobschmitt-civicactions** [CivicActions/fema-grants#82]
When analyst assigns a report to specialist, it generates an odd error

**Comment by bobschmitt-civicactions** [comment]
![screen shot 2018-02-16 at 2 36 42 pm](https://user-images.githubusercontent.com/22643607/36330482-026f3cb0-1327-11e8-8b35-2d618a6ee150.png)

![screen shot 2018-02-16 at 2 38 27 pm](https://user-images.githubusercontent.com/22643607/36330503-158cb868-1327-11e8-8fd6-8b1c8690fb9d.png)

**Comment by kevwalsh** [comment]
```

Message | Drupal\Component\Plugin\Exception\PluginNotFoundException: The "entity:workflow_transition:review_status" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 52 of /var/www/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
-- | --



```

**Comment by fmizzell** [comment]
This thread mentions that simply clearing the cache will fix this issue: https://www.drupal.org/node/2626646

I confirmed that things worked after "drush cr".

**Comment by grugnog** [comment]
Confirmed this issue and that drush cr fixes this. Added to drupal-install script.
