### ISSUE TITLE
Create Report content type

### ISSUE THREAD

**Issue by kevwalsh** [CivicActions/fema-grants#9]
https://www.grants.gov/web/grants/forms/postaward-fid.html?formId=532 contains the field definitions

We'll want the field collections module in there so that we can group the fields as well.

**Comment by kevwalsh** [comment]
i just noticed my first comment... i meant field _groups_ not collections :)

**Comment by fmizzell** [comment]
#64 points at some issues, so that can be considered the follow up ticket. We should have a separate ticket for creating a better layout of the form, that will include adding the module you mentioned @kevwalsh.
